# Generated by Django 5.2 on 2026-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_million'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('place_of_residence', models.CharField(max_length=200)),
                ('job_applied_for', models.CharField(max_length=50)),
                ('numbers_of_years_experience', models.IntegerField()),
                ('message', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
