# Generated by Django 5.2 on 2026-04-19 16:50

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_employmentmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='titleImage',
            field=models.ImageField(default='coming.jpg', storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='project_images/'),
        ),
    ]
